# See more config options https://github.com/gakonst/foundry/tree/master/config

[profile.default]
remappings = [
    "@forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "v2-palm/=v2-palm/contracts/"
]

[profile.ci.fuzz]
runs = 10_000

[rpc_endpoints]
1 = "${MAINNET_RPC_URL}"
10 = "${OPTIMISM_RPC_URL}"
56 = "${BNB_RPC_URL}"
100 = "${GNOSIS_RPC_URL}"
137 = "${POLYGON_RPC_URL}"
42161 = "${ARBITRUM_ONE_RPC_URL}"

5 = "${GOERLI_RPC_URL}"
420 = "${OPTIMISM_GOERLI_RPC_URL}"
80001 = "${MUMBAI_RPC_URL}"
421613 = "${ARBITRUM_GOERLI_RPC_URL}"